name: tests

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.4, 8.3]
        laravel: [ 12.*, 11.*, 10.*, 9.* ]
        dependency-version: [prefer-stable]
        include:
          - laravel: 12.*
            testbench: 10.*
            phpunit_config: phpunit.dist.xml
          - laravel: 11.*
            testbench: 9.*
            phpunit_config: phpunit.dist.xml
          - laravel: 10.*
            testbench: 8.*
            phpunit_config: phpunit.dist.xml
          - laravel: 9.*
            testbench: 7.*
            phpunit_config: phpunit_9.xml

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: quest
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: psr, mbstring, dom, fileinfo, mysql
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Run composer
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Run tests
        run: vendor/bin/phpunit -c ${{ matrix.phpunit_config }}
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
